Repository Kumoh-talk/YABAM-Festival-Backend, pull requests merged in 2025-04, with the labels that each got.

#11 Store 오픈/마감 도메인 로직 작성 및 Sale 도메인 모델링
  common/base/src/main/java/com/exception/ErrorCode.java
  domain/domain-pos/src/main/java/domain/pos/store/entity/Sale.java
  domain/domain-pos/src/main/java/domain/pos/store/entity/Store.java
  domain/domain-pos/src/main/java/domain/pos/store/implement/SaleReader.java
  domain/domain-pos/src/main/java/domain/pos/store/implement/SaleWriter.java
  domain/domain-pos/src/main/java/domain/pos/store/implement/StoreValidator.java
  domain/domain-pos/src/main/java/domain/pos/store/implement/StoreWriter.java
  domain/domain-pos/src/main/java/domain/pos/store/repository/SaleRepository.java
  domain/domain-pos/src/main/java/domain/pos/store/repository/StoreRepository.java
  domain/domain-pos/src/main/java/domain/pos/store/service/SaleService.java
  domain/domain-pos/src/main/java/domain/pos/store/service/StoreService.java
  domain/domain-pos/src/test/java/domain/pos/store/service/SaleServiceTest.java
  domain/domain-pos/src/test/java/domain/pos/store/service/StoreServiceTest.java
  domain/domain-pos/src/test/java/fixtures/store/SaleFixture.java
  domain/domain-pos/src/test/java/fixtures/store/StoreFixture.java
Labels: feature

#13 Table 도메인 엔티티 설계 및 테이블 생성 로직 구현
  common/base/src/main/java/com/exception/ErrorCode.java
  domain/domain-pos/src/main/java/domain/pos/store/implement/StoreValidator.java
  domain/domain-pos/src/main/java/domain/pos/store/service/SaleService.java
  domain/domain-pos/src/main/java/domain/pos/store/service/StoreService.java
  domain/domain-pos/src/main/java/domain/pos/table/entity/Table.java
  domain/domain-pos/src/main/java/domain/pos/table/implement/TableHandler.java
  domain/domain-pos/src/main/java/domain/pos/table/repository/TableRepository.java
  domain/domain-pos/src/main/java/domain/pos/table/service/TableService.java
  domain/domain-pos/src/test/java/domain/pos/store/service/SaleServiceTest.java
  domain/domain-pos/src/test/java/domain/pos/store/service/StoreServiceTest.java
  domain/domain-pos/src/test/java/domain/pos/table/service/TableServiceTest.java
  domain/domain-pos/src/test/java/fixtures/table/TableFixture.java
  rule-config/naver-checkstyle-rules.xml
Labels: feature

#15 메뉴 상세조회/수정/삭제 도메인 로직 구현
  domain/domain-pos/src/main/java/domain/pos/menu/implement/MenuValidator.java
  domain/domain-pos/src/main/java/domain/pos/menu/implement/MenuWriter.java
  domain/domain-pos/src/main/java/domain/pos/menu/repository/MenuRepository.java
  domain/domain-pos/src/main/java/domain/pos/menu/service/MenuService.java
  domain/domain-pos/src/test/java/domain/pos/menu/MenuServiceTest.java
  domain/domain-pos/src/test/java/fixtures/menu/MenuInfoFixture.java
Labels: feature

#17 order 생성 및 table 활성화 로직 구현
  common/base/src/main/java/com/exception/ErrorCode.java
  domain/domain-pos/src/main/java/domain/pos/member/entity/Customer.java
  domain/domain-pos/src/main/java/domain/pos/member/entity/Owner.java
  domain/domain-pos/src/main/java/domain/pos/member/implement/MemberHandler.java
  domain/domain-pos/src/main/java/domain/pos/member/repository/MemberRepository.java
  domain/domain-pos/src/main/java/domain/pos/member/repository/OwnerRepository.java
  domain/domain-pos/src/main/java/domain/pos/member/service/MemberService.java
  domain/domain-pos/src/main/java/domain/pos/order/entity/Order.java
  domain/domain-pos/src/main/java/domain/pos/order/implement/OrderHandler.java
  domain/domain-pos/src/main/java/domain/pos/order/implement/OrderWriter.java
  domain/domain-pos/src/main/java/domain/pos/order/repository/OrderRepository.java
  domain/domain-pos/src/main/java/domain/pos/order/service/OrderService.java
  domain/domain-pos/src/main/java/domain/pos/store/entity/Store.java
  domain/domain-pos/src/main/java/domain/pos/store/implement/StoreValidator.java
  domain/domain-pos/src/main/java/domain/pos/table/implement/TableReader.java
  domain/domain-pos/src/main/java/domain/pos/table/implement/TableWriter.java
  domain/domain-pos/src/main/java/domain/pos/table/repository/TableRepository.java
  domain/domain-pos/src/test/java/domain/pos/menu/MenuServiceTest.java
  domain/domain-pos/src/test/java/domain/pos/order/service/OrderServiceTest.java
  domain/domain-pos/src/test/java/fixtures/member/OwnerFixture.java
  domain/domain-pos/src/test/java/fixtures/order/OrderFixture.java
  domain/domain-pos/src/test/java/fixtures/store/StoreFixture.java
  domain/domain-pos/src/test/java/fixtures/table/TableFixture.java
Labels: feature

#18 order 도메인 receipt 도메인으로 변경
  domain/domain-pos/src/main/java/domain/pos/order/implement/OrderWriter.java
  domain/domain-pos/src/main/java/domain/pos/order/repository/OrderRepository.java
  domain/domain-pos/src/main/java/domain/pos/receipt/entity/Receipt.java
  domain/domain-pos/src/main/java/domain/pos/receipt/implement/ReceiptWriter.java
  domain/domain-pos/src/main/java/domain/pos/receipt/repository/ReceiptRepository.java
  domain/domain-pos/src/main/java/domain/pos/receipt/service/ReceiptService.java
  domain/domain-pos/src/test/java/domain/pos/receipt/service/ReceiptServiceTest.java
  domain/domain-pos/src/test/java/fixtures/receipt/ReceiptFixture.java
Labels: refactor

#19 테이블 crud 로직 구현
  common/base/src/main/java/com/exception/ErrorCode.java
  domain/domain-pos/src/main/java/domain/pos/table/implement/TableHandler.java
  domain/domain-pos/src/main/java/domain/pos/table/implement/TableReader.java
  domain/domain-pos/src/main/java/domain/pos/table/implement/TableWriter.java
  domain/domain-pos/src/main/java/domain/pos/table/repository/TableRepository.java
  domain/domain-pos/src/main/java/domain/pos/table/service/TableService.java
  domain/domain-pos/src/test/java/domain/pos/receipt/service/ReceiptServiceTest.java
  domain/domain-pos/src/test/java/domain/pos/store/service/SaleServiceTest.java
  domain/domain-pos/src/test/java/domain/pos/store/service/StoreServiceTest.java
  domain/domain-pos/src/test/java/domain/pos/table/service/TableServiceTest.java
  domain/domain-pos/src/test/java/fixtures/store/StoreFixture.java
Labels: feature, refactor

#20 영수증 RUD 도메인 로직 및 메뉴, 카테고리 리팩토링
  common/base/src/main/java/com/exception/ErrorCode.java
  domain/domain-pos/src/main/java/domain/pos/menu/entity/MenuCategory.java
  domain/domain-pos/src/main/java/domain/pos/menu/entity/MenuCategoryInfo.java
  domain/domain-pos/src/main/java/domain/pos/menu/entity/MenuInfo.java
  domain/domain-pos/src/main/java/domain/pos/menu/implement/MenuCategoryReader.java
  domain/domain-pos/src/main/java/domain/pos/menu/implement/MenuCategoryValidator.java
  domain/domain-pos/src/main/java/domain/pos/menu/implement/MenuCategoryWriter.java
  domain/domain-pos/src/main/java/domain/pos/menu/implement/MenuReader.java
  domain/domain-pos/src/main/java/domain/pos/menu/implement/MenuValidator.java
  domain/domain-pos/src/main/java/domain/pos/menu/repository/MenuCategoryRepository.java
  domain/domain-pos/src/main/java/domain/pos/menu/repository/MenuRepository.java
  domain/domain-pos/src/main/java/domain/pos/menu/service/MenuCategoryService.java
  domain/domain-pos/src/main/java/domain/pos/menu/service/MenuService.java
  domain/domain-pos/src/main/java/domain/pos/receipt/entity/Receipt.java
  domain/domain-pos/src/main/java/domain/pos/receipt/entity/ReceiptInfo.java
  domain/domain-pos/src/main/java/domain/pos/receipt/implement/ReceiptReader.java
  domain/domain-pos/src/main/java/domain/pos/receipt/implement/ReceiptWriter.java
  domain/domain-pos/src/main/java/domain/pos/receipt/repository/ReceiptRepository.java
  domain/domain-pos/src/main/java/domain/pos/receipt/service/ReceiptService.java
  domain/domain-pos/src/main/java/domain/pos/store/implement/SaleReader.java
  domain/domain-pos/src/main/java/domain/pos/store/repository/SaleRepository.java
  domain/domain-pos/src/test/java/domain/pos/menu/MenuCategoryServiceTest.java
  domain/domain-pos/src/test/java/domain/pos/menu/MenuServiceTest.java
  domain/domain-pos/src/test/java/domain/pos/receipt/service/ReceiptServiceTest.java
  domain/domain-pos/src/test/java/fixtures/member/UserFixture.java
  domain/domain-pos/src/test/java/fixtures/menu/MenuCategoryFixture.java
  domain/domain-pos/src/test/java/fixtures/menu/MenuCategoryInfoFixture.java
  domain/domain-pos/src/test/java/fixtures/menu/MenuInfoFixture.java
  domain/domain-pos/src/test/java/fixtures/receipt/ReceiptFixture.java
  domain/domain-pos/src/test/java/fixtures/receipt/ReceiptInfoFixture.java
Labels: feature, refactor

#21 pos 시스템 infra 모듈 jpa 설정 및 query dsl 설정 작업
  .gitignore
  build.gradle
  infra/rdb/pos/build.gradle
  infra/rdb/pos/docker/docker-compose.yml
  infra/rdb/pos/readme.md
  infra/rdb/pos/src/main/java/com/pos/config/InfraAutoConfig.java
  infra/rdb/pos/src/main/java/com/pos/config/JpaComponentConfig.java
  infra/rdb/pos/src/main/java/com/pos/config/JpaConfig.java
  infra/rdb/pos/src/main/java/com/pos/config/QueryDSLConfig.java
  infra/rdb/pos/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  infra/rdb/pos/src/main/resources/application.yml
  infra/rdb/pos/src/test/java/com/pos/config/RepositoryTest.java
  infra/rdb/pos/src/test/resources/application-test.yml
  settings.gradle
Labels: setting

#22 Store 엔티티 설계 및 Repository 구현 , Domain-pos 모듈 TestFixture 플러그인 세팅
  domain/domain-pos/build.gradle
  domain/domain-pos/src/main/java/domain/pos/store/entity/Store.java
  domain/domain-pos/src/main/java/domain/pos/store/entity/StoreInfo.java
  domain/domain-pos/src/test/java/domain/pos/menu/MenuCategoryServiceTest.java
  domain/domain-pos/src/test/java/domain/pos/menu/MenuServiceTest.java
  domain/domain-pos/src/test/java/domain/pos/receipt/service/ReceiptServiceTest.java
  domain/domain-pos/src/testFixtures/java/fixtures/member/UserFixture.java
  domain/domain-pos/src/testFixtures/java/fixtures/menu/MenuCategoryFixture.java
  domain/domain-pos/src/testFixtures/java/fixtures/menu/MenuCategoryInfoFixture.java
  domain/domain-pos/src/testFixtures/java/fixtures/menu/MenuFixture.java
  domain/domain-pos/src/testFixtures/java/fixtures/menu/MenuInfoFixture.java
  domain/domain-pos/src/testFixtures/java/fixtures/receipt/ReceiptFixture.java
  domain/domain-pos/src/testFixtures/java/fixtures/receipt/ReceiptInfoFixture.java
  domain/domain-pos/src/testFixtures/java/fixtures/store/SaleFixture.java
  domain/domain-pos/src/testFixtures/java/fixtures/store/StoreFixture.java
  domain/domain-pos/src/testFixtures/java/fixtures/store/StoreInfoFixture.java
  domain/domain-pos/src/testFixtures/java/fixtures/table/TableFixture.java
  infra/rdb/pos/build.gradle
  infra/rdb/pos/src/main/java/com/pos/global/base/entity/BaseEntity.java
  infra/rdb/pos/src/main/java/com/pos/global/config/InfraAutoConfig.java
  infra/rdb/pos/src/main/java/com/pos/global/config/JpaComponentConfig.java
  infra/rdb/pos/src/main/java/com/pos/global/config/JpaConfig.java
  infra/rdb/pos/src/main/java/com/pos/global/config/QueryDSLConfig.java
  infra/rdb/pos/src/main/java/com/pos/store/entity/StoreEntity.java
  infra/rdb/pos/src/main/java/com/pos/store/mapper/StoreMapper.java
  infra/rdb/pos/src/main/java/com/pos/store/repository/StoreJpaRepository.java
  infra/rdb/pos/src/main/java/com/pos/store/repository/StoreRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/store/vo/StorePoint.java
  infra/rdb/pos/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  infra/rdb/pos/src/test/java/com/pos/builder/BuilderSupporter.java
  infra/rdb/pos/src/test/java/com/pos/builder/TestFixtureBuilder.java
  infra/rdb/pos/src/test/java/com/pos/config/RepositoryTest.java
  infra/rdb/pos/src/test/java/com/pos/fixtures/store/StoreEntityFixture.java
  infra/rdb/pos/src/test/java/com/pos/global/config/RepositoryTest.java
  infra/rdb/pos/src/test/java/com/pos/store/repository/StoreRepositoryImplTest.java
  infra/rdb/pos/src/test/resources/application-test.yml
Labels: feature, setting

#23 주문 생성 및 주문 상태 변경 도메인 로직 구현
  common/base/src/main/java/com/exception/ErrorCode.java
  domain/domain-pos/src/main/java/domain/pos/menu/implement/MenuCategoryReader.java
  domain/domain-pos/src/main/java/domain/pos/menu/implement/MenuCategoryValidator.java
  domain/domain-pos/src/main/java/domain/pos/menu/implement/MenuReader.java
  domain/domain-pos/src/main/java/domain/pos/menu/implement/MenuValidator.java
  domain/domain-pos/src/main/java/domain/pos/menu/repository/MenuCategoryRepository.java
  domain/domain-pos/src/main/java/domain/pos/menu/repository/MenuRepository.java
  domain/domain-pos/src/main/java/domain/pos/menu/service/MenuCategoryService.java
  domain/domain-pos/src/main/java/domain/pos/menu/service/MenuService.java
  domain/domain-pos/src/main/java/domain/pos/order/entity/Order.java
  domain/domain-pos/src/main/java/domain/pos/order/entity/OrderMenu.java
  domain/domain-pos/src/main/java/domain/pos/order/entity/vo/OrderStatus.java
  domain/domain-pos/src/main/java/domain/pos/order/implement/OrderReader.java
  domain/domain-pos/src/main/java/domain/pos/order/implement/OrderWriter.java
  domain/domain-pos/src/main/java/domain/pos/order/repository/OrderRepository.java
  domain/domain-pos/src/main/java/domain/pos/order/service/OrderService.java
  domain/domain-pos/src/main/java/domain/pos/receipt/implement/ReceiptValidator.java
  domain/domain-pos/src/main/java/domain/pos/receipt/service/ReceiptService.java
  domain/domain-pos/src/test/java/domain/pos/menu/MenuCategoryServiceTest.java
  domain/domain-pos/src/test/java/domain/pos/menu/MenuServiceTest.java
  domain/domain-pos/src/test/java/domain/pos/order/implement/OrderWriterTest.java
  domain/domain-pos/src/test/java/domain/pos/order/service/OrderServiceTest.java
  domain/domain-pos/src/test/java/domain/pos/receipt/implement/ReceiptValidatorTest.java
  domain/domain-pos/src/test/java/domain/pos/receipt/service/ReceiptServiceTest.java
  domain/domain-pos/src/testFixtures/java/fixtures/member/UserFixture.java
  domain/domain-pos/src/testFixtures/java/fixtures/menu/MenuFixture.java
  domain/domain-pos/src/testFixtures/java/fixtures/order/OrderFixture.java
  domain/domain-pos/src/testFixtures/java/fixtures/order/OrderMenuFixture.java
  domain/domain-pos/src/testFixtures/java/fixtures/receipt/ReceiptFixture.java
Labels: feature, refactor

#25 테이블 infra 계층 구현
  common/base/src/main/java/com/exception/ErrorCode.java
  common/base/src/main/java/com/exception/VoException.java
  common/base/src/main/java/com/exception/handler/GlobalExceptionHandler.java
  domain/domain-pos/src/main/java/domain/pos/table/entity/Table.java
  domain/domain-pos/src/main/java/domain/pos/table/implement/TableReader.java
  domain/domain-pos/src/main/java/domain/pos/table/implement/TableWriter.java
  domain/domain-pos/src/main/java/domain/pos/table/repository/TableRepository.java
  domain/domain-pos/src/main/java/domain/pos/table/service/TableService.java
  domain/domain-pos/src/test/java/domain/pos/table/service/TableServiceTest.java
  infra/rdb/pos/build.gradle
  infra/rdb/pos/src/main/java/com/pos/store/entity/StoreEntity.java
  infra/rdb/pos/src/main/java/com/pos/store/mapper/StoreMapper.java
  infra/rdb/pos/src/main/java/com/pos/table/entity/TableEntity.java
  infra/rdb/pos/src/main/java/com/pos/table/mapper/TableMapper.java
  infra/rdb/pos/src/main/java/com/pos/table/repository/TableJpaRepository.java
  infra/rdb/pos/src/main/java/com/pos/table/repository/TableRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/table/repository/querydsl/TableDslRepository.java
  infra/rdb/pos/src/main/java/com/pos/table/repository/querydsl/TableDslRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/table/vo/TableNumber.java
  infra/rdb/pos/src/test/java/com/pos/builder/BuilderSupporter.java
  infra/rdb/pos/src/test/java/com/pos/builder/TestFixtureBuilder.java
  infra/rdb/pos/src/test/java/com/pos/fixtures/table/TableEntityFixture.java
  infra/rdb/pos/src/test/java/com/pos/store/repository/StoreRepositoryImplTest.java
  infra/rdb/pos/src/test/java/com/pos/table/entity/TableEntityTest.java
  infra/rdb/pos/src/test/java/com/pos/table/repository/TableRepositoryImplTest.java
Labels: feature

#26 Sale Entity 설계 및 Repository 구현
  domain/domain-pos/src/main/java/domain/pos/store/implement/SaleReader.java
  domain/domain-pos/src/main/java/domain/pos/store/repository/SaleRepository.java
  infra/rdb/pos/src/main/java/com/pos/global/config/JpaConfig.java
  infra/rdb/pos/src/main/java/com/pos/sale/entity/SaleEntity.java
  infra/rdb/pos/src/main/java/com/pos/sale/mapper/SaleMapper.java
  infra/rdb/pos/src/main/java/com/pos/sale/repository/SaleJpaRepository.java
  infra/rdb/pos/src/main/java/com/pos/sale/repository/SaleRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/table/entity/TableEntity.java
  infra/rdb/pos/src/test/java/com/pos/builder/BuilderSupporter.java
  infra/rdb/pos/src/test/java/com/pos/builder/TestFixtureBuilder.java
  infra/rdb/pos/src/test/java/com/pos/fixtures/sale/SaleFixture.java
  infra/rdb/pos/src/test/java/com/pos/sale/repository/SaleRepositoryImplTest.java
Labels: feature

#24 주문 조회 및 주문 메뉴 CRUD 도메인 로직 구현
  common/base/src/main/java/com/exception/ErrorCode.java
  domain/domain-pos/src/main/java/domain/pos/member/implement/UserPassportValidator.java
  domain/domain-pos/src/main/java/domain/pos/order/entity/OrderMenu.java
  domain/domain-pos/src/main/java/domain/pos/order/implement/OrderMenuReader.java
  domain/domain-pos/src/main/java/domain/pos/order/implement/OrderMenuWriter.java
  domain/domain-pos/src/main/java/domain/pos/order/implement/OrderReader.java
  domain/domain-pos/src/main/java/domain/pos/order/repository/OrderMenuRepository.java
  domain/domain-pos/src/main/java/domain/pos/order/repository/OrderRepository.java
  domain/domain-pos/src/main/java/domain/pos/order/service/OrderMenuService.java
  domain/domain-pos/src/main/java/domain/pos/order/service/OrderService.java
  domain/domain-pos/src/main/java/domain/pos/receipt/entity/Receipt.java
  domain/domain-pos/src/main/java/domain/pos/receipt/entity/ReceiptCustomer.java
  domain/domain-pos/src/main/java/domain/pos/receipt/entity/ReceiptInfo.java
  domain/domain-pos/src/main/java/domain/pos/receipt/implement/ReceiptCustomerWriter.java
  domain/domain-pos/src/main/java/domain/pos/receipt/implement/ReceiptReader.java
  domain/domain-pos/src/main/java/domain/pos/receipt/implement/ReceiptValidator.java
  domain/domain-pos/src/main/java/domain/pos/receipt/repository/ReceiptCustomerRepository.java
  domain/domain-pos/src/main/java/domain/pos/receipt/repository/ReceiptRepository.java
  domain/domain-pos/src/main/java/domain/pos/receipt/service/ReceiptService.java
  domain/domain-pos/src/main/java/domain/pos/store/implement/SaleReader.java
  domain/domain-pos/src/main/java/domain/pos/store/implement/SaleValidator.java
  domain/domain-pos/src/main/java/domain/pos/store/repository/SaleRepository.java
  domain/domain-pos/src/test/java/domain/pos/order/service/OrderMenuServiceTest.java
  domain/domain-pos/src/test/java/domain/pos/order/service/OrderServiceTest.java
  domain/domain-pos/src/test/java/domain/pos/receipt/implement/ReceiptValidatorTest.java
  domain/domain-pos/src/test/java/domain/pos/receipt/service/ReceiptServiceTest.java
  domain/domain-pos/src/testFixtures/java/fixtures/order/OrderMenuFixture.java
  domain/domain-pos/src/testFixtures/java/fixtures/receipt/ReceiptFixture.java
  infra/rdb/pos/src/main/java/com/pos/sale/repository/SaleRepositoryImpl.java
Labels: feature

#28 점주 실시간 주문 내역 갱신 서버 초기 개발 및 이벤트 모델링
  application/event/build.gradle
  application/event/src/main/java/com/event/EventApplication.java
  application/event/src/main/java/com/event/channel/OwnerStoreChannel.java
  application/event/src/main/java/com/event/controller/SsePosController.java
  application/event/src/main/java/com/event/implement/OwnerStoreValidator.java
  application/event/src/main/java/com/event/message/StoreOrderEvent.java
  application/event/src/main/java/com/event/service/SsePosService.java
  settings.gradle
Labels: feature

#29 SSE server Kafka Consumer 세팅 및 이벤트 및 Kafka 모듈화
  application/event/build.gradle
  application/event/src/main/java/com/event/channel/OwnerStoreChannel.java
  application/event/src/main/java/com/event/controller/SsePosController.java
  application/event/src/main/java/com/event/service/SsePosService.java
  application/event/src/main/resources/application.yml
  domain/domain-event/store-event/build.gradle
  domain/domain-event/store-event/src/main/java/com/pos/consumer/StoreOrderHandler.java
  domain/domain-event/store-event/src/main/java/com/pos/event/StoreOrderEvent.java
  domain/domain-pos/src/test/java/domain/pos/order/service/OrderServiceTest.java
  infra/mq/kafka-pos/build.gradle
  infra/mq/kafka-pos/src/main/java/com/pos/config/KafkaAutoConfig.java
  infra/mq/kafka-pos/src/main/java/com/pos/config/KafkaConsumerConfig.java
  infra/mq/kafka-pos/src/main/java/com/pos/consumer/store/order/KafkaStoreOrderEventListener.java
  infra/mq/kafka-pos/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  infra/mq/kafka-pos/src/main/resources/application.yml
  settings.gradle
Labels: feature, setting, refactor

#30 UserPassport 역직렬화 및 메서드 별 권한체크 AOP, 인터셉터 모듈 위치 재구성
  application/yabam/build.gradle
  application/yabam/src/main/java/com/application/festival/yabam/HelloController.java
  application/yabam/src/main/java/com/application/global/config/WebMvcConfig.java
  common/mvc/build.gradle
  common/mvc/src/main/java/com/aop/AssignUserPassportAspect.java
  common/mvc/src/main/java/com/authorization/AssignUserPassport.java
  common/mvc/src/main/java/com/authorization/HasRole.java
  common/mvc/src/main/java/com/config/WebMvcConfig.java
  common/mvc/src/main/java/com/interceptor/AuthorizationInterceptor.java
  common/mvc/src/main/java/com/interceptor/DeserializingUserPassportInterceptor.java
  common/mvc/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  domain/domain-pos/src/main/java/domain/pos/receipt/implement/ReceiptReader.java
  domain/domain-pos/src/main/java/domain/pos/receipt/repository/ReceiptRepository.java
  domain/domain-pos/src/main/java/domain/pos/receipt/service/ReceiptService.java
  settings.gradle
Labels: feature, refactor

#31 store , table , sale applicaiton 모듈 구현
  application/yabam/yabam-core/build.gradle
  application/yabam/yabam-core/docker-infra/docker-compose.yml
  application/yabam/yabam-core/src/main/java/com/application/YabamApplication.java
  application/yabam/yabam-core/src/main/java/com/application/festival/yabam/HelloController.java
  application/yabam/yabam-core/src/main/java/com/application/global/config/swagger/ApiErrorResponseExplanation.java
  application/yabam/yabam-core/src/main/java/com/application/global/config/swagger/ApiErrorResponseHandler.java
  application/yabam/yabam-core/src/main/java/com/application/global/config/swagger/ApiResponseExplanations.java
  application/yabam/yabam-core/src/main/java/com/application/global/config/swagger/ApiSuccessResponseExplanation.java
  application/yabam/yabam-core/src/main/java/com/application/global/config/swagger/ApiSuccessResponseHandler.java
  application/yabam/yabam-core/src/main/java/com/application/global/config/swagger/SwaggerConfig.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/sale/api/SaleApi.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/sale/controller/SaleController.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/sale/dto/response/SaleIdResponse.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/store/api/StoreApi.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/store/controller/StoreController.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/store/dto/request/StoreWriteRequest.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/store/dto/response/StoreIdResponse.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/store/dto/response/StoreInfoResponse.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/table/api/TableApi.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/table/controller/TableController.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/table/dto/TableInfoResponse.java
  application/yabam/yabam-core/src/main/resources/application.yml
  application/yabam/yabam-core/src/test/java/com/application/festival/yabam/YabamApplicationTests.java
  application/yabam/yabam-event/build.gradle
  application/yabam/yabam-event/src/main/java/com/event/EventApplication.java
  application/yabam/yabam-event/src/main/java/com/event/channel/OwnerStoreChannel.java
  application/yabam/yabam-event/src/main/java/com/event/controller/SsePosController.java
  application/yabam/yabam-event/src/main/java/com/event/implement/OwnerStoreValidator.java
  application/yabam/yabam-event/src/main/java/com/event/service/SsePosService.java
  application/yabam/yabam-event/src/main/resources/application.yml
  domain/domain-pos/src/main/java/domain/pos/store/repository/SaleRepository.java
  domain/domain-pos/src/main/java/domain/pos/store/repository/StoreRepository.java
  domain/domain-pos/src/main/java/domain/pos/table/repository/TableRepository.java
  settings.gradle
Labels: feature, refactor

#33 StoreOrder Event Producer 개발 및 카프카 모듈 리팩터링
  application/yabam/yabam-event/src/main/java/com/event/EventApplication.java
  domain/domain-event/store-event/src/main/java/com/pos/producer/StoreOrderProducer.java
  infra/mq/kafka-pos/build.gradle
  infra/mq/kafka-pos/src/main/java/com/pos/KafkaPosApplication.java
  infra/mq/kafka-pos/src/main/java/com/pos/config/KafkaAutoConfig.java
  infra/mq/kafka-pos/src/main/java/com/pos/consumer/store/order/KafkaStoreOrderEventListener.java
  infra/mq/kafka-pos/src/main/java/com/pos/consumer/store/order/config/KafkaConsumerConfig.java
  infra/mq/kafka-pos/src/main/java/com/pos/global/properties/KafkaStoreOrderProperties.java
  infra/mq/kafka-pos/src/main/java/com/pos/producer/store/order/KafkaStoreOrderProducer.java
  infra/mq/kafka-pos/src/main/java/com/pos/producer/store/order/config/KafkaProcuerConfig.java
  infra/mq/kafka-pos/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  infra/mq/kafka-pos/src/test/java/com/pos/consumer/store/order/KafkaStoreOrderEventListenerTest.java
  infra/mq/kafka-pos/src/test/resources/application-test.yml
Labels: feature

#36 table 수 수정 api 테이블 정보 반환하게 수정
  application/yabam/yabam-core/src/main/java/com/application/presentation/table/api/TableApi.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/table/controller/TableController.java
  domain/domain-pos/src/main/java/domain/pos/table/implement/TableWriter.java
  domain/domain-pos/src/main/java/domain/pos/table/repository/TableRepository.java
  domain/domain-pos/src/main/java/domain/pos/table/service/TableService.java
  infra/rdb/pos/src/main/java/com/pos/table/repository/TableRepositoryImpl.java
  infra/rdb/pos/src/test/java/com/pos/table/repository/TableRepositoryImplTest.java
Labels: refactor

#37 store 정보에 테이블 당 비용 정보 추가
  application/yabam/yabam-core/src/main/java/com/application/presentation/store/dto/request/StoreWriteRequest.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/store/dto/response/StoreInfoResponse.java
  domain/domain-pos/src/main/java/domain/pos/store/entity/StoreInfo.java
  domain/domain-pos/src/testFixtures/java/fixtures/store/StoreInfoFixture.java
  infra/rdb/pos/src/main/java/com/pos/store/entity/StoreEntity.java
  infra/rdb/pos/src/main/java/com/pos/store/mapper/StoreMapper.java
  infra/rdb/pos/src/main/java/com/pos/store/vo/TableCostPerTime.java
  infra/rdb/pos/src/test/java/com/pos/store/repository/StoreRepositoryImplTest.java
Labels: fix
