Repository Kumoh-talk/YABAM-Festival-Backend, pull requests merged in 2025-05, with the labels that each got.

#38 [#34] StoreOrder 이벤트 파이프라인 리팩터링 및 Producer 가이드 문서화 작업 완료
  .coderabbit.yaml
  application/yabam/yabam-event/README.md
  application/yabam/yabam-event/build.gradle
  application/yabam/yabam-event/src/main/java/com/event/channel/OwnerStoreChannel.java
  application/yabam/yabam-event/src/main/java/com/event/channel/SseChannel.java
  application/yabam/yabam-event/src/main/java/com/event/config/SseChannelConfig.java
  application/yabam/yabam-event/src/main/java/com/event/controller/SsePosController.java
  application/yabam/yabam-event/src/main/java/com/event/implement/EmitterGenerator.java
  application/yabam/yabam-event/src/main/java/com/event/service/SsePosService.java
  application/yabam/yabam-event/src/main/resources/application.yml
  domain/domain-event/store-event/src/main/java/com/pos/consumer/SseEventHandler.java
  domain/domain-event/store-event/src/main/java/com/pos/consumer/StoreOrderHandler.java
  domain/domain-event/store-event/src/main/java/com/pos/event/SseChannelProvider.java
  domain/domain-event/store-event/src/main/java/com/pos/event/StoreOrderEvent.java
  domain/domain-event/store-event/src/main/java/com/pos/producer/StoreOrderProducer.java
  domain/domain-pos/src/main/java/domain/pos/order/implement/StoreOrderProducer.java
  infra/mq/kafka-pos/README.md
  infra/mq/kafka-pos/build.gradle
  infra/mq/kafka-pos/src/main/java/com/pos/consumer/store/order/KafkaStoreOrderEventListener.java
  infra/mq/kafka-pos/src/main/java/com/pos/producer/store/order/KafkaStoreOrderProducer.java
  infra/mq/kafka-pos/src/main/java/com/pos/producer/store/order/common/StoreOrderEventMapper.java
  infra/mq/kafka-pos/src/main/java/com/pos/producer/store/order/config/KafkaProcuerConfig.java
  infra/mq/kafka-pos/src/test/java/com/pos/consumer/store/order/KafkaStoreOrderDtoEventListenerTest.java
Labels: feature, setting, refactor

#39 cart 기능 도메인 구현
  domain/domain-pos/src/main/java/domain/pos/cart/entity/Cart.java
  domain/domain-pos/src/main/java/domain/pos/cart/entity/CartMenu.java
  domain/domain-pos/src/main/java/domain/pos/cart/implement/CartWriter.java
  domain/domain-pos/src/main/java/domain/pos/cart/repository/CartRepository.java
  domain/domain-pos/src/main/java/domain/pos/cart/service/CartService.java
  domain/domain-pos/src/main/java/domain/pos/menu/implement/MenuReader.java
  domain/domain-pos/src/main/java/domain/pos/menu/repository/MenuRepository.java
  domain/domain-pos/src/test/java/domain/pos/cart/service/CartServiceTest.java
  domain/domain-pos/src/testFixtures/java/fixtures/cart/CartFixture.java
  infra/rdb/pos/src/main/java/com/pos/menu/repository/impl/MenuRepositoryImpl.java
Labels: feature

#40 Receipt 서비스 로직 수정, 추가 및 인프라 로직 구현
  domain/domain-pos/src/main/java/domain/pos/menu/repository/MenuCategoryRepository.java
  domain/domain-pos/src/main/java/domain/pos/menu/repository/MenuRepository.java
  domain/domain-pos/src/main/java/domain/pos/order/entity/Order.java
  domain/domain-pos/src/main/java/domain/pos/order/repository/OrderRepository.java
  domain/domain-pos/src/main/java/domain/pos/order/service/OrderService.java
  domain/domain-pos/src/main/java/domain/pos/receipt/entity/Receipt.java
  domain/domain-pos/src/main/java/domain/pos/receipt/entity/ReceiptInfo.java
  domain/domain-pos/src/main/java/domain/pos/receipt/implement/ReceiptCustomerWriter.java
  domain/domain-pos/src/main/java/domain/pos/receipt/implement/ReceiptReader.java
  domain/domain-pos/src/main/java/domain/pos/receipt/implement/ReceiptWriter.java
  domain/domain-pos/src/main/java/domain/pos/receipt/repository/ReceiptCustomerRepository.java
  domain/domain-pos/src/main/java/domain/pos/receipt/repository/ReceiptRepository.java
  domain/domain-pos/src/main/java/domain/pos/receipt/service/ReceiptService.java
  domain/domain-pos/src/main/java/domain/pos/table/implement/TableReader.java
  domain/domain-pos/src/main/java/domain/pos/table/repository/TableRepository.java
  domain/domain-pos/src/test/java/domain/pos/order/service/OrderServiceTest.java
  domain/domain-pos/src/test/java/domain/pos/receipt/service/ReceiptServiceTest.java
  domain/domain-pos/src/testFixtures/java/fixtures/receipt/ReceiptFixture.java
  domain/domain-pos/src/testFixtures/java/fixtures/receipt/ReceiptInfoFixture.java
  infra/rdb/pos/src/main/java/com/pos/order/entity/OrderEntity.java
  infra/rdb/pos/src/main/java/com/pos/order/entity/OrderMenuEntity.java
  infra/rdb/pos/src/main/java/com/pos/order/mapper/OrderMapper.java
  infra/rdb/pos/src/main/java/com/pos/order/mapper/OrderMenuMapper.java
  infra/rdb/pos/src/main/java/com/pos/order/repository/jpa/OrderJpaRepository.java
  infra/rdb/pos/src/main/java/com/pos/order/repository/querydsl/OrderQueryDslRepository.java
  infra/rdb/pos/src/main/java/com/pos/order/repository/querydsl/OrderQueryDslRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/receipt/entity/ReceiptCustomerEntity.java
  infra/rdb/pos/src/main/java/com/pos/receipt/entity/ReceiptEntity.java
  infra/rdb/pos/src/main/java/com/pos/receipt/mapper/ReceiptCustomerMapper.java
  infra/rdb/pos/src/main/java/com/pos/receipt/mapper/ReceiptMapper.java
  infra/rdb/pos/src/main/java/com/pos/receipt/repository/impl/ReceiptCustomerRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/receipt/repository/impl/ReceiptRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/receipt/repository/jpa/ReceiptCustomerJpaRepository.java
  infra/rdb/pos/src/main/java/com/pos/receipt/repository/jpa/ReceiptJpaRepository.java
  infra/rdb/pos/src/main/java/com/pos/receipt/repository/querydsl/ReceiptQueryDslRepository.java
  infra/rdb/pos/src/main/java/com/pos/receipt/repository/querydsl/ReceiptQueryDslRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/sale/entity/SaleEntity.java
  infra/rdb/pos/src/main/java/com/pos/table/entity/TableEntity.java
  infra/rdb/pos/src/main/java/com/pos/table/repository/TableRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/table/repository/querydsl/TableDslRepository.java
  infra/rdb/pos/src/main/java/com/pos/table/repository/querydsl/TableDslRepositoryImpl.java
  infra/rdb/pos/src/test/java/com/pos/table/repository/TableRepositoryImplTest.java
Labels: feature, refactor

#41 장바구니 infra application 모듈 구현
  .coderabbit.yaml
  application/yabam/yabam-core/src/main/java/com/application/festival/yabam/HelloController.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/cart/api/CartApi.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/cart/controller/CartController.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/cart/dto/response/CartInfoResponse.java
  domain/domain-pos/src/main/java/domain/pos/cart/implement/CartWriter.java
  domain/domain-pos/src/main/java/domain/pos/cart/repository/CartRepository.java
  domain/domain-pos/src/main/java/domain/pos/cart/service/CartService.java
  domain/domain-pos/src/main/java/domain/pos/menu/implement/MenuReader.java
  domain/domain-pos/src/test/java/domain/pos/cart/service/CartServiceTest.java
  infra/rdb/pos/src/main/java/com/pos/cart/entity/CartEntity.java
  infra/rdb/pos/src/main/java/com/pos/cart/entity/CartMenuEntity.java
  infra/rdb/pos/src/main/java/com/pos/cart/mapper/CartMapper.java
  infra/rdb/pos/src/main/java/com/pos/cart/repository/CartJpaRepository.java
  infra/rdb/pos/src/main/java/com/pos/cart/repository/CartMenuJpaRepository.java
  infra/rdb/pos/src/main/java/com/pos/cart/repository/dsl/CartDslRepository.java
  infra/rdb/pos/src/main/java/com/pos/cart/repository/dsl/CartDslRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/cart/repository/impl/CartRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/order/entity/OrderMenuEntity.java
  infra/rdb/pos/src/test/java/com/pos/builder/BuilderSupporter.java
  infra/rdb/pos/src/test/java/com/pos/builder/TestFixtureBuilder.java
  infra/rdb/pos/src/test/java/com/pos/cart/repository/impl/CartRepositoryImplTest.java
  infra/rdb/pos/src/test/java/com/pos/fixtures/cart/CartFixture.java
Labels: feature, refactor, fix

#43 리뷰 crud 구현
  application/yabam/yabam-core/build.gradle
  application/yabam/yabam-core/src/main/java/com/application/presentation/review/api/ReviewApi.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/review/controller/ReviewController.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/review/dto/request/ReviewCreateRequest.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/review/dto/request/ReviewCusorRequest.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/review/dto/request/ReviewUpdateRequest.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/review/dto/response/ReviewIdResponse.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/review/dto/response/ReviewsCusorResponse.java
  common/base/src/main/java/com/exception/ErrorCode.java
  domain/domain-pos/src/main/java/domain/pos/review/entity/Review.java
  domain/domain-pos/src/main/java/domain/pos/review/entity/ReviewInfo.java
  domain/domain-pos/src/main/java/domain/pos/review/implement/ReviewReader.java
  domain/domain-pos/src/main/java/domain/pos/review/implement/ReviewWriter.java
  domain/domain-pos/src/main/java/domain/pos/review/repository/ReviewRepository.java
  domain/domain-pos/src/main/java/domain/pos/review/service/ReviewService.java
  domain/domain-pos/src/test/java/domain/pos/review/service/ReviewServiceTest.java
  domain/domain-pos/src/testFixtures/java/fixtures/member/UserFixture.java
  domain/domain-pos/src/testFixtures/java/fixtures/review/ReviewFixture.java
  infra/rdb/pos/src/main/java/com/pos/review/entity/ReviewEntity.java
  infra/rdb/pos/src/main/java/com/pos/review/entity/vo/ReviewUser.java
  infra/rdb/pos/src/main/java/com/pos/review/mapper/ReviewMapper.java
  infra/rdb/pos/src/main/java/com/pos/review/repository/dsl/ReviewDslRepository.java
  infra/rdb/pos/src/main/java/com/pos/review/repository/dsl/ReviewDslRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/review/repository/impl/ReviewRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/review/repository/jpa/ReviewJpaRepository.java
Labels: feature

#45 Order, OrderMenu Infra 로직 구현 및 일부 도메인 서비스 로직 리팩토링
  common/base/src/main/java/com/exception/ErrorCode.java
  domain/domain-pos/src/main/java/domain/pos/cart/implement/CartWriter.java
  domain/domain-pos/src/main/java/domain/pos/menu/entity/Menu.java
  domain/domain-pos/src/main/java/domain/pos/menu/entity/MenuCategoryInfo.java
  domain/domain-pos/src/main/java/domain/pos/menu/implement/MenuReader.java
  domain/domain-pos/src/main/java/domain/pos/menu/implement/MenuWriter.java
  domain/domain-pos/src/main/java/domain/pos/menu/repository/MenuRepository.java
  domain/domain-pos/src/main/java/domain/pos/menu/service/MenuCategoryService.java
  domain/domain-pos/src/main/java/domain/pos/menu/service/MenuService.java
  domain/domain-pos/src/main/java/domain/pos/order/entity/Order.java
  domain/domain-pos/src/main/java/domain/pos/order/entity/OrderMenu.java
  domain/domain-pos/src/main/java/domain/pos/order/entity/vo/OrderMenuStatus.java
  domain/domain-pos/src/main/java/domain/pos/order/entity/vo/OrderStatus.java
  domain/domain-pos/src/main/java/domain/pos/order/event/OrderEventListener.java
  domain/domain-pos/src/main/java/domain/pos/order/event/OrderMenuStatusChangedEvent.java
  domain/domain-pos/src/main/java/domain/pos/order/implement/OrderMenuReader.java
  domain/domain-pos/src/main/java/domain/pos/order/implement/OrderMenuWriter.java
  domain/domain-pos/src/main/java/domain/pos/order/implement/OrderReader.java
  domain/domain-pos/src/main/java/domain/pos/order/implement/OrderWriter.java
  domain/domain-pos/src/main/java/domain/pos/order/repository/OrderMenuRepository.java
  domain/domain-pos/src/main/java/domain/pos/order/repository/OrderRepository.java
  domain/domain-pos/src/main/java/domain/pos/order/service/OrderMenuService.java
  domain/domain-pos/src/main/java/domain/pos/order/service/OrderService.java
  domain/domain-pos/src/main/java/domain/pos/receipt/implement/ReceiptReader.java
  domain/domain-pos/src/main/java/domain/pos/receipt/repository/ReceiptRepository.java
  domain/domain-pos/src/main/java/domain/pos/receipt/service/ReceiptService.java
  domain/domain-pos/src/test/java/domain/pos/menu/MenuServiceTest.java
  domain/domain-pos/src/test/java/domain/pos/order/implement/OrderWriterTest.java
  domain/domain-pos/src/test/java/domain/pos/order/service/OrderMenuServiceTest.java
  domain/domain-pos/src/test/java/domain/pos/order/service/OrderServiceTest.java
  domain/domain-pos/src/testFixtures/java/fixtures/order/OrderFixture.java
  infra/rdb/pos/src/main/java/com/pos/menu/entity/MenuEntity.java
  infra/rdb/pos/src/main/java/com/pos/menu/mapper/MenuMapper.java
  infra/rdb/pos/src/main/java/com/pos/menu/repository/impl/MenuRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/menu/repository/querydsl/MenuQueryDslRepository.java
  infra/rdb/pos/src/main/java/com/pos/menu/repository/querydsl/MenuQueryDslRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/order/entity/OrderEntity.java
  infra/rdb/pos/src/main/java/com/pos/order/entity/OrderMenuEntity.java
  infra/rdb/pos/src/main/java/com/pos/order/mapper/OrderMapper.java
  infra/rdb/pos/src/main/java/com/pos/order/mapper/OrderMenuMapper.java
  infra/rdb/pos/src/main/java/com/pos/order/repository/impl/OrderMenuRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/order/repository/impl/OrderRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/order/repository/jpa/OrderMenuJpaRepository.java
  infra/rdb/pos/src/main/java/com/pos/order/repository/querydsl/OrderMenuQueryDslRepository.java
  infra/rdb/pos/src/main/java/com/pos/order/repository/querydsl/OrderMenuQueryDslRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/order/repository/querydsl/OrderQueryDslRepository.java
  infra/rdb/pos/src/main/java/com/pos/order/repository/querydsl/OrderQueryDslRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/receipt/entity/ReceiptEntity.java
  infra/rdb/pos/src/main/java/com/pos/receipt/mapper/ReceiptMapper.java
  infra/rdb/pos/src/main/java/com/pos/receipt/repository/impl/ReceiptRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/receipt/repository/querydsl/ReceiptQueryDslRepository.java
  infra/rdb/pos/src/main/java/com/pos/receipt/repository/querydsl/ReceiptQueryDslRepositoryImpl.java
  infra/rdb/pos/src/test/java/com/pos/menu/repository/MenuRepositoryImplTest.java
Labels: feature, refactor

#51 로컬 개발환경 docker 세팅 및 uuid 랜덤 난수 생성기 성능 트러블 슈팅
  application/gateway/docker-compose/docker-compose.yml
  application/yabam/yabam-core/docker-infra/docker-compose.yml
  application/yabam/yabam-core/docker-infra/docker/mysql/initdb/01-create-authdb.sql
  utils/util-uuid/src/main/java/com/uuid/UuidUtils.java
  utils/util-uuid/src/test/java/com/uuid/UuidUtilsTest.java
Labels: feature, error, fix

#54 store 목록 조회 및 review 목록 조회 api 오류 해결
  application/yabam/yabam-core/src/main/java/com/application/presentation/review/controller/ReviewController.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/store/api/StoreApi.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/store/controller/StoreController.java
  infra/rdb/pos/src/main/java/com/pos/review/repository/dsl/ReviewDslRepositoryImpl.java
Labels: error, fix

#57 유저 관련 추가 api 구현 및 자잘한 설정 리팩토링
  application/auth/build.gradle
  application/auth/src/main/java/com/auth/domain/implement/JwtOidcProvider.java
  application/auth/src/main/java/com/auth/domain/implement/OAuthOidcHelper.java
  application/auth/src/main/java/com/auth/domain/implement/UserHandler.java
  application/auth/src/main/java/com/auth/domain/repository/UserRepository.java
  application/auth/src/main/java/com/auth/domain/service/UserService.java
  application/auth/src/main/java/com/auth/infra/oidc/property/OidcClientProperties.java
  application/auth/src/main/java/com/auth/infra/oidc/property/apple/AppleOidcProperties.java
  application/auth/src/main/java/com/auth/infra/oidc/property/google/GoogleOidcProperties.java
  application/auth/src/main/java/com/auth/infra/oidc/property/kakao/KakaoOidcProperties.java
  application/auth/src/main/java/com/auth/infra/user/entity/UserEntity.java
  application/auth/src/main/java/com/auth/infra/user/repository/UserRepositoryImpl.java
  application/auth/src/main/java/com/auth/presentation/api/UserApi.java
  application/auth/src/main/java/com/auth/presentation/controller/UserController.java
  application/auth/src/main/java/com/auth/presentation/dto/response/UserInfoResponse.java
  application/gateway/src/main/java/com/gateway/component/JwtIssueFunction.java
  application/gateway/src/main/java/com/gateway/config/SecurityConfig.java
  application/gateway/src/main/java/com/gateway/controller/AuthApi.java
  application/gateway/src/main/java/com/gateway/controller/AuthController.java
  application/gateway/src/main/java/com/gateway/controller/RefreshRequest.java
  application/gateway/src/main/java/com/gateway/jwt/JwtHandler.java
  application/gateway/src/main/java/com/gateway/service/AuthService.java
  application/gateway/src/main/resources/yabam-ssl.p12
  common/base/src/main/java/com/exception/ErrorCode.java
  infra/rdb/pos/src/main/java/com/pos/order/repository/querydsl/OrderQueryDslRepositoryImpl.java
Labels: feature, error, refactor

#59 기획 변경으로 인한 리뷰 작성 로직 수정 및 store 조회 dsl 에러 수정
  application/yabam/yabam-core/src/main/java/com/application/presentation/review/api/ReviewApi.java
  domain/domain-pos/src/main/java/domain/pos/review/service/ReviewService.java
  domain/domain-pos/src/test/java/domain/pos/review/service/ReviewServiceTest.java
  infra/rdb/pos/src/main/java/com/pos/store/entity/StoreEntity.java
  infra/rdb/pos/src/main/java/com/pos/store/mapper/StoreMapper.java
  infra/rdb/pos/src/main/java/com/pos/store/repository/StoreRepositoryImpl.java
Labels: error, fix

#60 내가 등록한 가게 조회 api 개발 완료
  application/yabam/yabam-core/src/main/java/com/application/presentation/store/api/StoreApi.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/store/controller/StoreController.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/store/dto/response/MyStoreResopnse.java
  domain/domain-pos/src/main/java/domain/pos/store/implement/StoreReader.java
  domain/domain-pos/src/main/java/domain/pos/store/repository/StoreRepository.java
  domain/domain-pos/src/main/java/domain/pos/store/service/StoreService.java
  infra/rdb/pos/src/main/java/com/pos/store/repository/StoreRepositoryImpl.java
Labels: feature

#62 로그인 오류 해결 및 receipt id UUID로 변경
  application/auth/src/main/java/com/auth/presentation/dto/request/OidcLoginRequest.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/cart/api/CartApi.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/cart/controller/CartController.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/cart/dto/response/CartInfoResponse.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/order/api/OrderApi.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/order/controller/OrderController.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/receipt/api/ReceiptApi.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/receipt/controller/ReceiptController.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/receipt/dto/response/ReceiptIdResponse.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/receipt/dto/response/ReceiptInfoResponse.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/review/dto/request/ReviewCreateRequest.java
  common/base/src/main/java/com/exception/ErrorCode.java
  domain/domain-pos/src/main/java/domain/pos/cart/entity/Cart.java
  domain/domain-pos/src/main/java/domain/pos/cart/implement/CartWriter.java
  domain/domain-pos/src/main/java/domain/pos/cart/repository/CartRepository.java
  domain/domain-pos/src/main/java/domain/pos/cart/service/CartService.java
  domain/domain-pos/src/main/java/domain/pos/order/implement/OrderReader.java
  domain/domain-pos/src/main/java/domain/pos/order/repository/OrderRepository.java
  domain/domain-pos/src/main/java/domain/pos/order/service/OrderService.java
  domain/domain-pos/src/main/java/domain/pos/receipt/entity/ReceiptInfo.java
  domain/domain-pos/src/main/java/domain/pos/receipt/implement/ReceiptCustomerWriter.java
  domain/domain-pos/src/main/java/domain/pos/receipt/implement/ReceiptReader.java
  domain/domain-pos/src/main/java/domain/pos/receipt/implement/ReceiptValidator.java
  domain/domain-pos/src/main/java/domain/pos/receipt/implement/ReceiptWriter.java
  domain/domain-pos/src/main/java/domain/pos/receipt/repository/ReceiptCustomerRepository.java
  domain/domain-pos/src/main/java/domain/pos/receipt/repository/ReceiptRepository.java
  domain/domain-pos/src/main/java/domain/pos/receipt/service/ReceiptService.java
  domain/domain-pos/src/main/java/domain/pos/review/implement/ReviewReader.java
  domain/domain-pos/src/main/java/domain/pos/review/repository/ReviewRepository.java
  domain/domain-pos/src/main/java/domain/pos/review/service/ReviewService.java
  domain/domain-pos/src/main/java/domain/pos/store/implement/StoreValidator.java
  domain/domain-pos/src/test/java/domain/pos/cart/service/CartServiceTest.java
  domain/domain-pos/src/test/java/domain/pos/order/service/OrderServiceTest.java
  domain/domain-pos/src/test/java/domain/pos/review/service/ReviewServiceTest.java
  domain/domain-pos/src/testFixtures/java/fixtures/cart/CartFixture.java
  domain/domain-pos/src/testFixtures/java/fixtures/receipt/ReceiptInfoFixture.java
  infra/rdb/pos/src/main/java/com/pos/cart/mapper/CartMapper.java
  infra/rdb/pos/src/main/java/com/pos/cart/repository/dsl/CartDslRepository.java
  infra/rdb/pos/src/main/java/com/pos/cart/repository/dsl/CartDslRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/cart/repository/impl/CartRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/order/repository/impl/OrderRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/order/repository/querydsl/OrderQueryDslRepository.java
  infra/rdb/pos/src/main/java/com/pos/order/repository/querydsl/OrderQueryDslRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/receipt/entity/ReceiptCustomerEntity.java
  infra/rdb/pos/src/main/java/com/pos/receipt/entity/ReceiptEntity.java
  infra/rdb/pos/src/main/java/com/pos/receipt/repository/impl/ReceiptCustomerRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/receipt/repository/impl/ReceiptRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/receipt/repository/jpa/ReceiptJpaRepository.java
  infra/rdb/pos/src/main/java/com/pos/receipt/repository/querydsl/ReceiptQueryDslRepository.java
  infra/rdb/pos/src/main/java/com/pos/receipt/repository/querydsl/ReceiptQueryDslRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/review/repository/dsl/ReviewDslRepository.java
  infra/rdb/pos/src/main/java/com/pos/review/repository/dsl/ReviewDslRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/review/repository/impl/ReviewRepositoryImpl.java
Labels: refactor, fix

#64 테이블 생성 수정 api 변경 삭제 api 추가
  application/yabam/yabam-core/src/main/java/com/application/presentation/receipt/dto/response/ReceiptResponse.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/table/api/TableApi.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/table/controller/TableController.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/table/dto/request/TableCreateRequest.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/table/dto/request/TableModifyRequest.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/table/dto/response/TableIdResponse.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/table/dto/response/TableInfoResponse.java
  domain/domain-pos/src/main/java/domain/pos/table/entity/Table.java
  domain/domain-pos/src/main/java/domain/pos/table/entity/TablePoint.java
  domain/domain-pos/src/main/java/domain/pos/table/implement/TableReader.java
  domain/domain-pos/src/main/java/domain/pos/table/implement/TableWriter.java
  domain/domain-pos/src/main/java/domain/pos/table/repository/TableRepository.java
  domain/domain-pos/src/main/java/domain/pos/table/service/TableService.java
  domain/domain-pos/src/test/java/domain/pos/table/service/TableServiceTest.java
  domain/domain-pos/src/testFixtures/java/fixtures/table/TableFixture.java
  infra/rdb/pos/src/main/java/com/pos/table/entity/TableEntity.java
  infra/rdb/pos/src/main/java/com/pos/table/mapper/TableMapper.java
  infra/rdb/pos/src/main/java/com/pos/table/repository/TableRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/table/repository/querydsl/TableDslRepository.java
  infra/rdb/pos/src/main/java/com/pos/table/repository/querydsl/TableDslRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/table/vo/TablePointVo.java
  infra/rdb/pos/src/test/java/com/pos/builder/TestFixtureBuilder.java
  infra/rdb/pos/src/test/java/com/pos/fixtures/table/TableEntityFixture.java
  infra/rdb/pos/src/test/java/com/pos/table/entity/TableEntityTest.java
  infra/rdb/pos/src/test/java/com/pos/table/repository/TableRepositoryImplTest.java
Labels: feature, fix

#67 s3 연동 및 presigned url 생성 api 구현
  application/yabam/yabam-core/build.gradle
  application/yabam/yabam-core/src/main/java/com/application/global/validator/EnumValidator.java
  application/yabam/yabam-core/src/main/java/com/application/global/validator/ValidEnum.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/store/api/StoreApi.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/store/controller/StoreController.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/store/dto/request/StorePresignedUrlRequest.java
  domain/domain-pos/build.gradle
  domain/domain-pos/src/main/java/domain/pos/store/entity/vo/StoreImageProperty.java
  domain/domain-pos/src/main/java/domain/pos/store/implement/StoreImageHandler.java
  domain/domain-pos/src/main/java/domain/pos/store/repository/PresignedUrlGenerator.java
  domain/domain-pos/src/main/java/domain/pos/store/service/StoreService.java
  infra/aws/infra-s3/build.gradle
  infra/aws/infra-s3/src/main/java/com/s3/component/S3PresignedUrlGenerator.java
  infra/aws/infra-s3/src/main/java/com/s3/config/S3AutoConfig.java
  infra/aws/infra-s3/src/main/java/com/s3/config/S3Config.java
  infra/aws/infra-s3/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  settings.gradle
  utils/util-url/build.gradle
  utils/util-url/src/main/java/com/url/UrlHandleUtil.java
Labels: feature

#69 #65, 66 장바구니 권한 체크 삭제 및 자잘한 수정
  application/yabam/yabam-core/src/main/java/com/application/presentation/call/controller/CallController.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/call/dto/request/CallCreateRequest.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/cart/controller/CartController.java
  domain/domain-pos/src/main/java/domain/pos/call/service/CallService.java
  domain/domain-pos/src/test/java/domain/pos/call/service/CallServiceTest.java
Labels: error, fix

#70 Receipt 리팩토링 및 잡다한 오류 수정
  application/yabam/yabam-core/src/main/java/com/application/presentation/cart/api/CartApi.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/receipt/api/ReceiptApi.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/receipt/controller/ReceiptController.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/receipt/dto/response/ReceiptAndOrdersResponse.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/receipt/dto/response/ReceiptResponse.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/receipt/dto/response/TableWithReceiptResponse.java
  domain/domain-pos/src/main/java/domain/pos/cart/entity/CartMenu.java
  domain/domain-pos/src/main/java/domain/pos/order/implement/OrderWriter.java
  domain/domain-pos/src/main/java/domain/pos/receipt/entity/Receipt.java
  domain/domain-pos/src/main/java/domain/pos/receipt/entity/ReceiptInfo.java
  domain/domain-pos/src/main/java/domain/pos/receipt/entity/TableWithNonAdjustReceipt.java
  domain/domain-pos/src/main/java/domain/pos/receipt/implement/ReceiptReader.java
  domain/domain-pos/src/main/java/domain/pos/receipt/repository/ReceiptRepository.java
  domain/domain-pos/src/main/java/domain/pos/receipt/service/ReceiptService.java
  domain/domain-pos/src/main/java/domain/pos/store/implement/SaleValidator.java
  domain/domain-pos/src/main/java/domain/pos/store/implement/StoreValidator.java
  infra/rdb/pos/src/main/java/com/pos/cart/repository/impl/CartRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/menu/entity/MenuEntity.java
  infra/rdb/pos/src/main/java/com/pos/menu/mapper/MenuMapper.java
  infra/rdb/pos/src/main/java/com/pos/order/repository/impl/OrderRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/receipt/repository/impl/ReceiptRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/receipt/repository/querydsl/ReceiptQueryDslRepository.java
  infra/rdb/pos/src/main/java/com/pos/receipt/repository/querydsl/ReceiptQueryDslRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/table/repository/TableRepositoryImpl.java
Labels: feature, error, refactor, fix

#71 #68 기획 변경으로 인한 리뷰 api deprecate 및 store 목록 조회 정보에 review 제외
  application/yabam/yabam-core/src/main/java/com/application/presentation/review/controller/ReviewController.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/store/api/StoreApi.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/store/controller/StoreController.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/store/dto/response/StoreCursorResponse.java
  domain/domain-pos/src/main/java/domain/pos/store/entity/dto/StoreHeadDto.java
  domain/domain-pos/src/main/java/domain/pos/store/implement/StoreReader.java
  domain/domain-pos/src/main/java/domain/pos/store/repository/StoreRepository.java
  domain/domain-pos/src/main/java/domain/pos/store/service/StoreService.java
  infra/rdb/pos/src/main/java/com/pos/store/mapper/StoreMapper.java
  infra/rdb/pos/src/main/java/com/pos/store/repository/StoreRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/store/repository/dsl/StoreDslRepository.java
  infra/rdb/pos/src/main/java/com/pos/store/repository/dsl/StoreDslRepositoryImpl.java
  infra/rdb/pos/src/test/java/com/pos/store/repository/StoreRepositoryImplTest.java
Labels: fix

#74 Order 리팩토링 및 잡다한 오류 수정
  application/yabam/yabam-core/src/main/java/com/application/presentation/menu/api/MenuApi.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/menu/api/MenuCategoryApi.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/menu/controller/MenuCategoryController.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/menu/controller/MenuController.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/order/api/OrderApi.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/order/api/OrderMenuApi.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/order/controller/OrderController.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/order/controller/OrderMenuController.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/receipt/api/ReceiptApi.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/receipt/controller/ReceiptController.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/sale/api/SaleApi.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/sale/controller/SaleController.java
  common/base/src/main/java/com/exception/ErrorCode.java
  domain/domain-pos/src/main/java/domain/pos/order/implement/OrderMenuReader.java
  domain/domain-pos/src/main/java/domain/pos/order/implement/OrderMenuWriter.java
  domain/domain-pos/src/main/java/domain/pos/order/implement/OrderReader.java
  domain/domain-pos/src/main/java/domain/pos/order/repository/OrderMenuRepository.java
  domain/domain-pos/src/main/java/domain/pos/order/repository/OrderRepository.java
  domain/domain-pos/src/main/java/domain/pos/order/service/OrderMenuService.java
  domain/domain-pos/src/main/java/domain/pos/order/service/OrderService.java
  domain/domain-pos/src/main/java/domain/pos/receipt/implement/ReceiptReader.java
  domain/domain-pos/src/main/java/domain/pos/receipt/repository/ReceiptRepository.java
  domain/domain-pos/src/main/java/domain/pos/receipt/service/ReceiptService.java
  domain/domain-pos/src/test/java/domain/pos/order/service/OrderMenuServiceTest.java
  domain/domain-pos/src/test/java/domain/pos/order/service/OrderServiceTest.java
  infra/rdb/pos/src/main/java/com/pos/order/mapper/OrderMenuMapper.java
  infra/rdb/pos/src/main/java/com/pos/order/repository/impl/OrderMenuRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/order/repository/impl/OrderRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/order/repository/querydsl/OrderMenuQueryDslRepository.java
  infra/rdb/pos/src/main/java/com/pos/order/repository/querydsl/OrderMenuQueryDslRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/order/repository/querydsl/OrderQueryDslRepository.java
  infra/rdb/pos/src/main/java/com/pos/order/repository/querydsl/OrderQueryDslRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/receipt/repository/impl/ReceiptRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/receipt/repository/querydsl/ReceiptQueryDslRepository.java
  infra/rdb/pos/src/main/java/com/pos/receipt/repository/querydsl/ReceiptQueryDslRepositoryImpl.java
  infra/rdb/pos/src/main/java/com/pos/sale/entity/SaleEntity.java
Labels: feature, error, refactor, fix

#75 image url store 대표 이미지 상세 이미지 메뉴 이미지 공통 presignedUrl api 로 리팩터링
  application/yabam/yabam-core/src/main/java/com/application/presentation/image/api/ImageApi.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/image/controller/ImageController.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/image/dto/request/PresignedUrlRequest.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/store/api/StoreApi.java
  application/yabam/yabam-core/src/main/java/com/application/presentation/store/controller/StoreController.java
  domain/domain-pos/src/main/java/domain/pos/image/entity/ImageProperty.java
  domain/domain-pos/src/main/java/domain/pos/image/service/ImageService.java
  domain/domain-pos/src/main/java/domain/pos/store/entity/vo/StoreImageProperty.java
  domain/domain-pos/src/main/java/domain/pos/store/service/StoreService.java
  utils/util-url/src/main/java/com/url/UrlHandleUtil.java
Labels: refactor, fix
